# Data training arguments
dataset_name: './load_data/dataset/foundation_merged_202504_train.json' #'./load_data/dataset/df_final_gudok_seed.json'
dataset_num_proc: 48
domain : "Amazon_Fashion"
# Model arguments
model_name_or_path: '/home/jovyan/cp-gpu-4-datavol-one-model/one-model-v4/one_model_v4_work/open-r1_20250411/data/google_gemma-3-1b-it_sft_001_amazon_Amazon_Fashion_lora'
hub_model_id: 'google_gemma-3-1b-it_sdpo_001_amazon_Amazon_Fashion'
output_dir: 'data/google_gemma-3-1b-it_sdpo_001_amazon_Amazon_Fashion'
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager #flash_attention_2 #flash_attention_2 #flash_attention_2
# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no' #'steps' #'no'
eval_steps: 10000 #25
gradient_accumulation_steps: 8
gradient_checkpointing: True #true-true가 원래 
gradient_checkpointing_kwargs:
  use_reentrant: True #false
hub_strategy: every_save
learning_rate: 5.0e-05 #5.0e-05 #5.0e-05 #1e-4
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: False
max_length: 12000
max_prompt_length: 500
# max_seq_length: 10000 #12000 #12000 #5000
max_steps: -1 #1400 # 무시 
num_train_epochs: 3 #3 #-1 # 2 #3
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 6 #12 # meta: 192, sr:16, srr:2 #3
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 50
save_total_limit: 1
seed: 42
use_liger: true
warmup_ratio: 0.05
use_peft: true
lora_target_modules: ['v_proj', 'q_proj', 'k_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj'] #['v_proj', 'q_proj'] #["q_proj", "v_proj"]
lora_alpha: 16
lora_r: 8 #8
lora_dropout : 0
bias : "none"
lora_task_type : "CAUSAL_LM"
load_in_8bit: True
optim: "paged_adamw_8bit"
# dataset_text_field: 'text'
trust_remote_code: True
use_liger_kernel: True
group_by_length : False
# dataloader_shuffle : True
# load_in_4bit: True
# bnb_4bit_quant_type : 'nf4'
# bnb_4bit_compute_dtype: bfloat16
